# Generated by Django 2.2 on 2019-04-28 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Controlador1', models.CharField(max_length=20)),
                ('Switch1', models.CharField(max_length=20)),
                ('Switch2', models.CharField(max_length=20)),
                ('HostIP1', models.CharField(max_length=20)),
                ('HostIP2', models.CharField(max_length=20)),
                ('HostIP3', models.CharField(max_length=20)),
                ('HostIP4', models.CharField(max_length=20)),
                ('HostNetmask1', models.CharField(max_length=20)),
                ('HostNetmask2', models.CharField(max_length=20)),
                ('HostNetmask3', models.CharField(max_length=20)),
                ('HostNetmask4', models.CharField(max_length=20)),
                ('HostGateway1', models.CharField(max_length=20)),
                ('HostGateway2', models.CharField(max_length=20)),
                ('HostGateway3', models.CharField(max_length=20)),
                ('HostGateway4', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
