# Generated by Django 2.2 on 2019-04-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologia', '0002_auto_20190427_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='rede',
            name='NomeRede',
            field=models.CharField(default='Nome da Topologia', max_length=30),
        ),
    ]
