# Generated by Django 2.2 on 2019-04-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologia', '0003_rede_nomerede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rede',
            name='NomeRede',
            field=models.CharField(default='Informe o nome da rede', max_length=30),
        ),
    ]
