# Generated by Django 2.2 on 2019-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologia', '0004_auto_20190428_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rede',
            old_name='Controlador1',
            new_name='RoteadorIP1',
        ),
        migrations.RenameField(
            model_name='rede',
            old_name='Switch1',
            new_name='RoteadorIP2',
        ),
        migrations.RenameField(
            model_name='rede',
            old_name='Switch2',
            new_name='RoteadorNetmask1',
        ),
        migrations.AddField(
            model_name='rede',
            name='RoteadorNetmask2',
            field=models.CharField(default='Informe a mascara do roteador 2', max_length=20),
        ),
    ]
